version: '3'
services:
  app:
    build: .
    ports:
      - 3111:3111
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - backend
volumes:
  mongo-data:
networks:
  backend